<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="3" tests="19" name="Default test" time="173.44" errors="0" timestamp="2024-11-24T18:06:57 IST">
  <testcase classname="Test_PACK.TC_RF_008" name="Verify_Registering_Account_by_entering_different_passwords_into_Password_and_Password_Confirm_fields" time="2.995"/>
  <testcase classname="Test_PACK.TC_RF_007" name="Verify__navigating_to_Register_Account_page_via_Login_page_NEW_Customer" time="0.965"/>
  <testcase classname="Test_PACK.TC_RF_007" name="Verify__navigating_to_Register_Account_page_via_Login_page_Register_Right_Box" time="1.056"/>
  <testcase classname="Test_PACK.TC_RF_007" name="Verify__navigating_to_Register_Account_page_via_MY_Account_Registration" time="0.589"/>
  <testcase classname="Test_PACK.TC_RF_009" name="Verify_Registering_Account_by_providing_the_existing_account_details" time="3.172"/>
  <testcase classname="Test_PACK.TC_RF_004" name="Verify_proper_notification_messages_with_no_data_in_the_madetory_field" time="4.853"/>
  <testcase classname="Test_PACK.TC_RF_003" name="verifyRegisteringAnAccount" time="4.573"/>
  <testcase classname="Test_PACK.TC_RF_014" name="Verify_all_mandatory_fields_in_Register_Account" time="1.074"/>
  <testcase classname="Test_PACK.TC_RF_006" name="Verify_Registering_an_Account_when_No_option_is_selected_for_Newsletter_field" time="3.717"/>
  <testcase classname="Test_PACK.TC_RF_005" name="Verify_Registering_an_Account_when_YES_option_is_selected_for_Newsletter_field" time="3.851"/>
  <testcase classname="Test_PACK.email_verification" name="test" time="11.135"/>
  <testcase classname="Test_PACK.TC_RF_011" name="Verify_Registering_Account_by_providing_invalid_phone_number_111" time="2.561">
    <failure type="java.lang.AssertionError" message="expected [https://tutorialsninja.com/demo/index.php?route=account/register] but found [https://tutorialsninja.com/demo/index.php?route=account/success]">
      <![CDATA[java.lang.AssertionError: expected [https://tutorialsninja.com/demo/index.php?route=account/register] but found [https://tutorialsninja.com/demo/index.php?route=account/success]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test_PACK.TC_RF_011.Verify_Registering_Account_by_providing_invalid_phone_number_111(TC_RF_011.java:41)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Verify_Registering_Account_by_providing_invalid_phone_number_111 -->
  <testcase classname="Test_PACK.TC_RF_011" name="Verify_Registering_Account_by_providing_invalid_phone_number_abcde" time="4.187">
    <failure type="java.lang.AssertionError" message="expected [https://tutorialsninja.com/demo/index.php?route=account/register] but found [https://tutorialsninja.com/demo/index.php?route=account/success]">
      <![CDATA[java.lang.AssertionError: expected [https://tutorialsninja.com/demo/index.php?route=account/register] but found [https://tutorialsninja.com/demo/index.php?route=account/success]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test_PACK.TC_RF_011.Verify_Registering_Account_by_providing_invalid_phone_number_abcde(TC_RF_011.java:76)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Verify_Registering_Account_by_providing_invalid_phone_number_abcde -->
  <testcase classname="Test_PACK.TC_RF_010" name="invalidEmail_1" time="1.745"/>
  <testcase classname="Test_PACK.TC_RF_010" name="invalidEmail_2" time="1.581"/>
  <testcase classname="Test_PACK.TC_RF_010" name="invalidEmail_3" time="2.931"/>
  <testcase classname="Test_PACK.TC_RF_010" name="invalidEmail_4" time="3.773"/>
  <testcase classname="Test_PACK.TC_RF_013" name="Verify_all_fields_in_the_Register_Account_page_have_proper_placeholders" time="0.965">
    <failure type="java.lang.AssertionError" message="expected [Password Confir] but found [Password Confirm]">
      <![CDATA[java.lang.AssertionError: expected [Password Confir] but found [Password Confirm]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at Test_PACK.TC_RF_013.Verify_all_fields_in_the_Register_Account_page_have_proper_placeholders(TC_RF_013.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- Verify_all_fields_in_the_Register_Account_page_have_proper_placeholders -->
  <testcase classname="Test_PACK.TC_RF_012" name="Verify_Registering_Account_by_using_Keyboard_keys" time="19.345"/>
</testsuite> <!-- Default test -->
